"""
Demo A: Your Model vs. the LLM
==================================

You will build a text classifier two ways and let them fight:

  A. Bag-of-words + logistic regression with scikit-learn — the library
     whose internals you built from scratch in homework 0.
  B. The Haiku LLM, zero training — you call the Claude API yourself and
     write the prompt that turns Haiku into a classifier.

The app scores both with the same yardstick and shows you where they
disagree. One thing to know: the reviews are SYNTHETIC, generated by the
code at the top of this file, and 20% of the test reviews are deliberately
ambiguous — so NO classifier can beat ~90% accuracy. Part 1 of the app
lets you choose how many positive and negative training reviews you get;
the test set is pinned so the two classifiers stay comparable.

THE WORKFLOW (same as homework 0)
---------------------------------
1. Work through the functions in the "YOUR CODE" section, top to bottom.
   Only the name, arguments, and a one-line description are given —
   figuring out the full specification is part of the homework.
2. Ask Haiku for help with the course tool:
       python tools/ask.py    (from the repository root)
   Remember it keeps NO memory — every prompt must be self-contained.
3. Run the app:   streamlit run <this file>
   It unlocks section by section as your functions start working.
4. Record your FINAL prompt in the comment above each function.
   MY_PROMPT (part B) needs no comment — the constant itself is your
   recorded prompt.

WHAT YOU SUBMIT
---------------
This single file: finished code plus the final prompt above each
function, plus your written answers in the header below.

YOUR ANSWERS (fill in after finishing)
--------------------------------------
Q1. Who won on accuracy, who won on AUC, and by how much?
    ...
Q2. Pick one review where the two classifiers disagree. Which one do you
    side with, and why?
    ...
Q3. Neither classifier can reach 90% accuracy on this data no matter
    what. Explain why in one or two sentences. (Reading the data
    generator below will help.)
    ...

RULES
-----
- Only edit the "YOUR CODE" section and the answers above.
- You may use numpy, scikit-learn, and requests.
- The LLM classifier must use the claude-haiku-4-5 model.

LEARNING GOALS
--------------
- Turn raw text into feature matrices without leaking test data
- Drive scikit-learn's estimator API: fit, transform, predict_proba
- Call a modern LLM API yourself and design its prompt
- Compare classical ML and LLMs honestly: accuracy, cost, control
"""

import csv
import inspect
import os
import pathlib
import re
from collections import Counter
from concurrent.futures import ThreadPoolExecutor

import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go
import requests
import streamlit as st
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve

HERE = pathlib.Path(__file__).resolve().parent

# ############################################################################
# ####################  THE DATA GENERATOR (read, don't edit)  ###############
# ############################################################################
# Every review is assembled from the pieces below: a product, two clauses,
# a connector, an optional hedge, and a sentence template.
#
#   - A "positive" review has a positive main clause (label 1). Its second
#     clause is negative with probability `concession`, otherwise neutral
#     (40% of the rest) or a second positive clause. "Negative" reviews
#     are the mirror image (label 0).
#   - An "ambiguous" review has a neutral main clause and a random-sentiment
#     aside, and its label is a COIN FLIP — the text carries no information.
#
# Since nothing can beat chance on the ambiguous reviews, the best possible
# ACCURACY is about  (1 - ambig_frac) * 1.0 + ambig_frac * 0.5  — with
# ambig_frac = 0.2 that is ~90%. The best possible AUC is higher (~0.98):
# a classifier that scores every ambiguous review exactly 0.5 ranks all
# clear reviews correctly and only ties the ambiguous ones with each
# other, i.e. AUC ≈ 1 - 0.5 * ambig_frac**2.
# The test set was generated ONCE at these settings and saved to test.csv.
# The TRAINING data is generated fresh each run with NO ambiguous reviews
# and NO concessions (see TRAIN_* below); Part 1 only lets you pick how many
# positive and negative reviews it has.

PRODUCTS = [
    "blood pressure monitor", "digital thermometer", "knee brace",
    "glucose meter", "pulse oximeter", "heating pad", "compression socks",
    "wrist splint", "nebulizer", "TENS unit", "shower chair", "cane",
    "hearing amplifier", "pill organizer", "posture corrector",
    "orthopedic pillow", "back massager", "first aid kit",
    "elastic bandage", "ice pack", "CPAP mask", "ankle support",
    "lumbar cushion", "foot spa", "walker", "grab bar",
]

POS_CLAUSES = [
    "the swelling went down within a few days",
    "readings are close to what the clinic gets",
    "my doctor was satisfied with the numbers",
    "the pain eased up noticeably after a week",
    "it held up fine through daily use",
    "setup was quick and the manual made sense",
    "the fit is snug without cutting off circulation",
    "battery lasts longer than I expected",
    "I sleep through the night more often now",
    "customer service replaced a part without fuss",
    "it feels sturdier than the one from the pharmacy",
    "my physical therapist approved of it",
    "the strap stays put even when I move around",
    "the display is bright enough to read without my glasses",
    "the readings matched the nurse's measurements exactly",
    "I can finally climb stairs without wincing",
    "the cushioning takes the pressure off my joints",
    "it charged fully in under an hour",
    "the alarm is loud enough to wake me but not the neighbors",
    "my blood sugar log has been steadier since I started using it",
    "the velcro still grips after dozens of washes",
    "the instructions were clear enough for my mother to follow",
    "it packs flat and fits in my carry-on",
    "the seams have not frayed at all",
    "the pharmacist said it was the brand she recommends",
    "my ankle feels supported without feeling locked in",
    "the heat spreads evenly instead of in hot spots",
    "I stopped needing the stronger painkillers",
    "the buttons are big enough to press with stiff fingers",
    "it survived being dropped on the bathroom tile",
    "the readings agree with the one at my doctor's office",
    "the gel stays cold for the whole twenty minutes",
    "the compression is firm but I forget I am wearing it",
    "my range of motion improved within two weeks",
    "the app syncs without any fiddling",
    "the mask seals well and does not leak",
    "my knee has stopped clicking when I stand up",
    "the material breathes so I do not sweat under it",
    "I recommended it to two people in my support group",
    "the memory function makes tracking my numbers easy",
    "it folds up small enough for my nightstand drawer",
    "my back pain is down to a dull ache most days",
    "the tubing has not kinked or cracked",
    "the warranty replacement arrived in three days",
    "the nozzle is easy to clean between uses",
    "the straps adjust to fit over a bulky sweater",
    "the numbers line up with my lab results",
    "it was worth every cent of the price",
]

NEG_CLAUSES = [
    "it stopped working after about a week",
    "the readings jump around between measurements",
    "the strap digs in and leaves marks",
    "the display is too dim to read in daylight",
    "the plastic clip cracked on the second use",
    "it runs through batteries at an alarming rate",
    "my skin got irritated where it touches",
    "the sizing chart is misleading",
    "the alarm goes off for no reason",
    "customer service never answered my emails",
    "it feels flimsier than the price suggests",
    "returning it was a hassle",
    "the readings are ten points off from the clinic's",
    "the velcro stopped gripping after a few washes",
    "the swelling came right back once I took it off",
    "the manual is a single badly translated sheet",
    "the cushioning flattened within a month",
    "it takes forever to charge and dies by lunchtime",
    "the fit is so tight it cut off circulation",
    "my doctor told me not to trust the numbers",
    "the seams split along the edge",
    "the heat only reaches one corner of the pad",
    "the buttons are too small for stiff fingers",
    "it slides down my leg every time I walk",
    "the gel leaked through the outer layer",
    "the alarm is too quiet to wake me",
    "the app loses my history every update",
    "the pain is no better than before I bought it",
    "the hinge squeaks with every step",
    "the compression is uneven and bunches behind the knee",
    "the tubing kinked and cracked within weeks",
    "the smell of the plastic has not gone away",
    "the memory function erased itself when the battery died",
    "the mask leaks around the nose",
    "the nozzle is impossible to clean properly",
    "the warranty claim was denied over a technicality",
    "my physical therapist told me to stop using it",
    "the material traps sweat and gets clammy",
    "the numbers disagree with my lab results",
    "the straps are too short to fit over clothing",
    "it rattled loose after being dropped once",
    "the gel warms up in about five minutes",
    "my range of motion got worse while wearing it",
    "the box arrived with a part missing",
    "the cuff inflates so hard it bruises my arm",
    "the screen scratched the first week",
    "the pharmacist had never heard of the brand",
    "I went back to the stronger painkillers",
]

NEUTRAL_CLAUSES = [
    "it does roughly what the box says",
    "results vary from day to day",
    "hard to tell if it makes a real difference",
    "my experience has been up and down",
    "some days it seems to help, some days not",
    "it is about what you would expect at this price",
    "I have only used it a handful of times",
    "the jury is still out for me",
    "it works, though I am not sure it matters",
    "I might keep it, I might return it",
    "my spouse thinks it helps more than I do",
    "compared to my old one, the difference is small",
    "I cannot tell whether the readings are right or not",
    "it is neither better nor worse than the pharmacy brand",
    "I use it when I remember, which is not often",
    "the pain comes and goes regardless",
    "it looks like every other one on the shelf",
    "my doctor shrugged when I showed it to her",
    "the strap is fine, the rest I have no opinion on",
    "it is a thing that exists and I own it now",
    "the readings are plausible but I have nothing to compare them to",
    "I am still in the trial period",
    "some features I use, most I ignore",
    "it does the job on paper",
    "my numbers look about the same as before",
    "I keep forgetting to charge it so I cannot say much",
    "the fit is okay, not great, not bad",
    "I am told it takes months to see a difference",
    "it sits in the drawer most of the week",
    "the manual says one thing, the app says another",
    "I could take it or leave it",
    "the price seems fair for what it is",
    "my therapist had no strong opinion either way",
    "it is hard to say whether the swelling changed",
    "I notice it less than I expected to, for better or worse",
    "the battery life is average as far as I can tell",
    "the display is readable, the numbers I cannot vouch for",
    "it is my third one of these and they all blur together",
    "maybe it works, maybe it is the new medication",
    "I wear it some nights and skip others",
    "the pressure is what I would call medium",
    "it replaced an older model that did about the same",
    "time will tell, as my doctor keeps saying",
    "I have nothing bad to say and nothing good either",
    "it arrived, it works, that is the extent of my review",
    "the heat is warm-ish, which is apparently the point",
    "my numbers are within range but they were before too",
    "I bought it on a recommendation and have no verdict yet",
]

HEDGES = ["Honestly,", "To be fair,", "For what it's worth,",
          "After a month,", "So far,", "I hate to say it, but",
          "Look,", "In my experience,", "Not gonna lie,", "Quick update:",
          "Three weeks in,", "Full disclosure,", "", "", ""]

CONNECT_POS = ["and", "plus", "and honestly", "and on top of that"]
CONNECT_MIX = ["but", "although", "even if", "that said,", "though",
               "on the other hand"]

# {Main} is the main clause with its first letter capitalized.
TEMPLATES = [
    "{hedge} this {product}: {main}, {conn} {other}.",
    "{hedge} {main} with this {product}, {conn} {other}.",
    "Bought this {product} a while back. {Main}, {conn} {other}.",
    "{Main}, {conn} {other}. That is my experience with this {product}.",
    "{hedge} {main}, {conn} {other}. Still deciding about the {product}.",
    "Review of my {product}: {main}; {conn} {other}.",
]


def _cap(s):
    return s[0].upper() + s[1:]


def _compose(rng, product, main, other, connector):
    text = rng.choice(TEMPLATES).format(
        hedge=rng.choice(HEDGES), product=product, main=main,
        Main=_cap(main), conn=connector, other=other)
    return _cap(" ".join(text.split()))


def make_review(rng, kind, concession):
    """kind: 'pos', 'neg', or 'ambig'. Returns (text, label)."""
    product = rng.choice(PRODUCTS)
    if kind in ("pos", "neg"):
        same, opposite = ((POS_CLAUSES, NEG_CLAUSES) if kind == "pos"
                          else (NEG_CLAUSES, POS_CLAUSES))
        main = rng.choice(same)
        r = rng.random()
        if r < concession:
            text = _compose(rng, product, main, rng.choice(opposite), rng.choice(CONNECT_MIX))
        elif r < concession + 0.4 * (1 - concession):
            text = _compose(rng, product, main, rng.choice(NEUTRAL_CLAUSES), rng.choice(CONNECT_MIX))
        else:
            text = _compose(rng, product, main, rng.choice(same), rng.choice(CONNECT_POS))
        return text, int(kind == "pos")
    # ambiguous: neutral core, one random-sentiment aside, random label
    main = rng.choice(NEUTRAL_CLAUSES)
    aside = rng.choice(POS_CLAUSES) if rng.random() < 0.5 else rng.choice(NEG_CLAUSES)
    if rng.random() < 0.5:
        text = _compose(rng, product, main, aside, rng.choice(CONNECT_MIX))
    else:
        text = _compose(rng, product, aside, rng.choice(NEUTRAL_CLAUSES), rng.choice(CONNECT_MIX))
    return text, int(rng.random() < 0.5)


@st.cache_data
def make_split(n_pos, n_neg, n_ambig, concession, seed):
    """Generate n_pos clear-positive, n_neg clear-negative and n_ambig
    ambiguous reviews, shuffled. Returns (texts, labels, kinds) where kinds
    is an array of 'clear' / 'ambiguous' — the app uses it to show the ceiling."""
    rng = np.random.default_rng(seed)
    plan = ["pos"] * n_pos + ["neg"] * n_neg + ["ambig"] * n_ambig
    rows = [make_review(rng, k, concession) + (k,) for k in plan]
    rng.shuffle(rows)
    texts = [t for t, _, _ in rows]
    labels = np.array([l for _, l, _ in rows])
    kinds = np.array(["ambiguous" if k == "ambig" else "clear" for _, _, k in rows])
    return texts, labels, kinds


# The test set never changes: it was generated once with the settings below
# and saved to test.csv next to this file. Every run reads that file, so
# Haiku's scores from Part 4 stay comparable while you change the training
# data in Part 1. (Delete test.csv to regenerate it.)
TEST_N, TEST_AMBIG, TEST_CONCESSION, TEST_SEED = 100, 0.2, 0.2, 20260908
TEST_CSV = HERE / "test.csv"

# The training data is cleaner than the test data: every review is clear and
# none contains a concession. Only how many positives and how many
# negatives you get is chosen in the app.
TRAIN_CONCESSION, TRAIN_SEED = 0.0, 1


@st.cache_data
def load_test_set():
    """Read test.csv; generate and save it first if it does not exist yet."""
    if not TEST_CSV.exists():
        n_ambig = int(round(TEST_N * TEST_AMBIG))
        n_clear = TEST_N - n_ambig
        texts, labels, kinds = make_split(n_clear // 2, n_clear - n_clear // 2, n_ambig,
                                          TEST_CONCESSION, TEST_SEED)
        with open(TEST_CSV, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["text", "label", "kind"])
            w.writerows(zip(texts, labels, kinds))
    rows = list(csv.DictReader(open(TEST_CSV, newline="")))
    return ([r["text"] for r in rows], np.array([int(r["label"]) for r in rows]),
            np.array([r["kind"] for r in rows]))


# Two word clouds of the test set, rendered ONCE and saved next to this file
# (the `wordcloud` package is only needed to regenerate them: delete the PNGs).
# A word is sized by how often it appears in that class AND how exclusive to
# that class it is, and the generator's scaffolding (templates, hedges,
# connectors, product names) is left out — otherwise both clouds would be
# dominated by "the", "review", "bought", which the two classes share.
CLOUD_PNGS = {1: HERE / "test_cloud_positive.png", 0: HERE / "test_cloud_negative.png"}


def class_word_counts(texts, labels):
    """{label: Counter of words} with stopwords and generator scaffolding removed."""
    scaffold = " ".join(TEMPLATES + HEDGES + CONNECT_POS + CONNECT_MIX + PRODUCTS)
    skip = set(ENGLISH_STOP_WORDS) | set(re.findall(r"[a-z']+", scaffold.lower()))
    return {c: Counter(w for t, y in zip(texts, labels) if y == c
                       for w in re.findall(r"[a-z']+", t.lower())
                       if w not in skip and len(w) > 2)
            for c in (0, 1)}


def load_word_clouds(texts, labels):
    """Return {label: png path}; render the PNGs first if they do not exist."""
    if all(p.exists() for p in CLOUD_PNGS.values()):
        return CLOUD_PNGS
    from wordcloud import WordCloud
    counts = class_word_counts(texts, labels)
    for c, path in CLOUD_PNGS.items():
        mine, other = counts[c], counts[1 - c]
        weights = {w: n * (n / (n + other[w])) ** 2 for w, n in mine.items() if n >= 2}
        WordCloud(width=800, height=450, background_color="white",
                  colormap="Greens" if c == 1 else "Reds", max_words=80,
                  random_state=0).generate_from_frequencies(weights).to_file(path)
    return CLOUD_PNGS

# ############################################################################
# ############################  YOUR CODE  ###################################
# ############################################################################
# Work top to bottom. Replace each placeholder body, and record your final
# prompt in the comment above each function.


# ── vectorize ───────────────────────────────────────────────────────────────
# MY FINAL PROMPT TO HAIKU:
# (replace this line with the prompt that produced your working function)
def vectorize(train_texts, test_texts, vocab_size):
    """Turn both text lists into word-count matrices over ONE vocabulary of
    the `vocab_size` most frequent training words.
    Return (vectorizer, X_train, X_test)."""
    return None, None, None  # placeholder


# ── train_classifier ────────────────────────────────────────────────────────
# MY FINAL PROMPT TO HAIKU:
# (replace this line with the prompt that produced your working function)
def train_classifier(X_train, y_train, pos_weight):
    """Train scikit-learn logistic regression and return the fitted model.
    `pos_weight` is the class weight of label 1 relative to label 0 (1.0 =
    treat both classes the same)."""
    return None  # placeholder


# ── predict_probs ───────────────────────────────────────────────────────────
# MY FINAL PROMPT TO HAIKU:
# (replace this line with the prompt that produced your working function)
def predict_probs(model, X):
    """Return a 1-D array: the model's probability of class 1 for each row."""
    return np.full(X.shape[0], 0.5)  # placeholder


# ── ask_haiku ───────────────────────────────────────────────────────────────
# MY FINAL PROMPT TO HAIKU:
# (replace this line with the prompt that produced your working function)
def ask_haiku(api_key, prompt, texts):
    """Send `prompt` plus a BATCH of reviews (`texts`, a list of up to 10
    strings) to the claude-haiku-4-5 model via the Claude API in ONE
    stateless call, and return a list of integer scores 0-100, one per
    review, in the same order. A review whose score cannot be parsed from
    the reply should come back as 50."""
    return [50] * len(texts)  # placeholder


# ── MY_PROMPT ───────────────────────────────────────────────────────────────
# This constant IS your recorded prompt for part B — design it yourself.
# It is sent to Haiku together with each batch of 10 reviews by ask_haiku().
# It must tell Haiku how to label its answers so ask_haiku() can match
# each score to its review.
MY_PROMPT = ""  # placeholder — write your classification prompt here


# ############################################################################
# ########################  APP SHELL (do not edit)  #########################
# ############################################################################
# Everything below is the user interface. It unlocks section by section as
# your functions start working. You don't need to understand Streamlit.


@st.cache_data(show_spinner="Computing the t-SNE map (a few seconds, cached)...")
def tsne_embed(X_dense):
    return TSNE(n_components=2, perplexity=30, random_state=0,
                init="pca").fit_transform(X_dense)


st.set_page_config(page_title="Demo A: Model vs LLM", page_icon="🥊", layout="wide")
st.title("Demo A: Your Model vs. the LLM")
st.markdown("""
Train a **bag-of-words logistic regression** (scikit-learn — the library whose
internals you built in homework 0) on medical product reviews, then make the
**Haiku LLM** classify the same reviews, and score both with the same
yardstick. Sections unlock as your functions start working.
""")

# ================================================================ Part 1
st.markdown("---")
st.header("Part 1: The data")

st.markdown("""
The reviews are **synthetic** — assembled by the generator at the top of this
file from a bank of positive, negative and neutral clauses. Read it: every
quirk you see below comes from there. The training reviews are all
**clear** (no coin-flip labels, no concessions); the sliders at the start of
Part 2 only set how many positive and how many negative ones you get.
The **test** set is harder.
""")

# The sample reviews go here, but they depend on the training sliders at
# the start of Part 2, so the box is filled in once the training data exists.
samples_box = st.container()

test_texts, test_y, test_kind = load_test_set()

# The best any classifier can do on the test set: perfect on the clear
# reviews, a coin flip (score 0.5) on the ambiguous ones.
n_ambig_test = int(np.sum(test_kind == "ambiguous"))
ceiling_acc = (len(test_y) - 0.5 * n_ambig_test) / len(test_y)
oracle = np.where(test_kind == "clear", test_y.astype(float), 0.5)
ceiling_auc = roc_auc_score(test_y, oracle)

st.markdown(f"""
The **pinned test set of {len(test_texts)}** reviews ({TEST_AMBIG:.0%} ambiguous,
saved in test.csv) never changes — so Haiku's scores in Part 4 stay
comparable while you move the sliders. Because the ambiguous test
reviews carry no signal, the best possible test **accuracy is
{ceiling_acc:.0%}** and the best possible **AUC is {ceiling_auc:.3f}**.
""")
clouds = load_word_clouds(test_texts, test_y)
c1, c2 = st.columns(2)
c1.image(str(clouds[1]), caption="Positive test reviews (label 1)", width="stretch")
c2.image(str(clouds[0]), caption="Negative test reviews (label 0)", width="stretch")
st.caption("Word clouds of the pinned test set. A word is sized by how often it "
           "appears in that class AND how exclusive it is to that class, so the "
           "words both classes share (\"the\", \"my\", \"it\") fade out. Compare "
           "with the words your model will pick in Part 2.")

# Which way each test-set word leans: log((count in positive + 1) /
# (count in negative + 1)) over words that appear at least 4 times. Used to
# highlight the sample reviews above.
counts = class_word_counts(test_texts, test_y)
words = [w for w in set(counts[0]) | set(counts[1]) if counts[0][w] + counts[1][w] >= 4]
lean = {w: np.log((counts[1][w] + 1) / (counts[0][w] + 1)) for w in words}
lean_max = max(abs(v) for v in lean.values())

def mark_lean(match):
    token = match.group(0).lower()
    if token in lean and lean[token] != 0:
        alpha = 0.2 + 0.5 * abs(lean[token]) / lean_max
        rgb = "44,160,44" if lean[token] > 0 else "214,39,40"
        return (f"<span style='background: rgba({rgb},{alpha:.2f}); "
                f"border-radius:3px; padding:0 2px'>{match.group(0)}</span>")
    return match.group(0)

# ================================================================ Part 2
st.markdown("---")
st.header("Part 2: Your model")

# ------------------------------------------------- training data sliders
st.subheader("Your training data")
c1, c2 = st.columns(2)
with c1:
    n_pos = st.slider("Positive training reviews", 50, 500, 300, 50)
with c2:
    n_neg = st.slider("Negative training reviews", 50, 500, 300, 50)

train_texts, train_y, train_kind = make_split(n_pos, n_neg, 0, TRAIN_CONCESSION, TRAIN_SEED)
keep = np.array([t not in set(test_texts) for t in train_texts])
train_texts = [t for t, k in zip(train_texts, keep) if k]
train_y, train_kind = train_y[keep], train_kind[keep]

# Five training reviews, shown at the top of Part 1, with every word that
# leans in the test set highlighted: green leans positive, red negative.
with samples_box:
    st.markdown("**Five of your training reviews**, with the leaning words marked:")
    sample_idx = np.random.default_rng(3).choice(len(train_texts), 5, replace=False)
    for i in sample_idx:
        st.html("<blockquote style='margin:0.4em 0; padding:0.3em 1em; "
                "border-left: 3px solid #ccc; line-height:1.8'>"
                + re.sub(r"[A-Za-z']+", mark_lean, train_texts[i])
                + f"<br><span style='color:{'#2ca02c' if train_y[i] == 1 else '#d62728'}'>"
                  f"— label: <b>{train_y[i]}</b></span>"
                "</blockquote>")
    st.caption("green = word leans positive in the test set · red = leans negative · "
               "stronger colour = stronger lean. Unmarked words appear fewer than 4 "
               "times in the test set.")

st.subheader("Model hyperparameters")
c1, c2 = st.columns(2)
with c1:
    vocab_size = st.slider("Vocabulary size (most frequent words)", 50, 600, 300, 50,
                           help="How many of the most frequent training words become "
                                "features. Every other word is invisible to the model.")
with c2:
    log_w = st.slider("Class weight of the positive class (log10)", -1.0, 1.0, 0.0, 0.1,
                      help="Log10 of the weight: -1 = 0.1×, 0 = 1× (both classes equal), "
                           "+1 = 10×. How much a positive training review counts "
                           "relative to a negative one when fitting.")
    pos_weight = float(10 ** log_w)
    st.caption(f"weight = 10^{log_w:+.1f} = **{pos_weight:.2f}×**")

vectorize_out = vectorize(train_texts, test_texts, vocab_size)
if vectorize_out is None or any(v is None for v in vectorize_out):
    st.warning("Locked — implement `vectorize()` to continue.")
    st.stop()
vectorizer, Xtr, Xte = vectorize_out
if Xtr.shape[0] != len(train_texts) or Xte.shape[0] != len(test_texts):
    st.error(f"`vectorize()` returned {Xtr.shape[0]} train / {Xte.shape[0]} test "
             f"rows; expected {len(train_texts)} / {len(test_texts)}.")
    st.stop()
if Xtr.shape[1] != Xte.shape[1]:
    st.error(f"`vectorize()` returned train and test matrices with different "
             f"column counts ({Xtr.shape[1]} vs {Xte.shape[1]}) — both must use "
             "the SAME vocabulary, learned from the training texts only.")
    st.stop()

model = train_classifier(Xtr, train_y, pos_weight)
if model is None:
    st.warning("Features OK! Now implement `train_classifier()`.")
    st.stop()

p_test = np.asarray(predict_probs(model, Xte), dtype=float)
if np.all(p_test == 0.5):
    st.warning("Model trained! Now implement `predict_probs()`.")
    st.stop()
if np.all(np.isin(p_test, [0.0, 1.0])):
    st.error("`predict_probs()` returned only 0s and 1s — those are hard "
             "labels. The app needs probabilities.")
    st.stop()

vocab = vectorizer.get_feature_names_out()
w = model.coef_[0]
model_pred = (p_test >= 0.5).astype(int)
model_acc = float(np.mean(model_pred == test_y))

# ------------------------------------------------- confusion matrix
# Counts at the 0.5 threshold. Each cell also shows the review the model was
# most confident about in that cell, so you can see what the cell MEANS.
st.subheader("Confusion matrix (test set, threshold 0.5)")

cells = {}  # (true, pred) -> indices
for t in (0, 1):
    for pr in (0, 1):
        cells[(t, pr)] = np.where((test_y == t) & (model_pred == pr))[0]
tn, fp = len(cells[(0, 0)]), len(cells[(0, 1)])
fn, tp = len(cells[(1, 0)]), len(cells[(1, 1)])
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

CELL_NAMES = {(0, 0): ("TN", "True negative"), (0, 1): ("FP", "False positive"),
              (1, 0): ("FN", "False negative"), (1, 1): ("TP", "True positive")}

def cell_html(t, pr):
    idx = cells[(t, pr)]
    n, total = len(idx), int(np.sum(test_y == t))
    right = t == pr
    rate = n / total
    # Only the edge is coloured: green if right, red if wrong, and its opacity
    # is the cell's rate (0 -> invisible, 1 -> solid). Fixed height so the
    # four cells line up whatever the example sentence's length.
    border = f"rgba({'44,160,44' if right else '214,39,40'},{rate:.2f})"
    label_color = "#2ca02c" if right else "#d62728"
    html = (f"<div style='border:6px solid {border}; border-radius:8px; "
            f"padding:10px 14px; height:260px; box-sizing:border-box; overflow-y:auto'>"
            f"<div><span style='font-size:1.8rem; font-weight:bold; color:{label_color}'>"
            f"{CELL_NAMES[(t, pr)][0]}</span> "
            f"<span style='color:#666'>({CELL_NAMES[(t, pr)][1]})</span></div>"
            f"<div style='font-size:1.4rem'>{n} / {total} = {n / total:.2f}</div>"
            f"<div style='color:#666; font-size:0.85rem'>of the {total} reviews that are "
            f"truly {t}, the model said {pr} for {n}</div>")
    if n:
        # the review the model was most confident about, in this cell
        i = idx[np.argmax(p_test[idx])] if pr == 1 else idx[np.argmin(p_test[idx])]
        html += (f"<div style='margin-top:6px; font-size:0.9rem; font-style:italic'>"
                 f"“{test_texts[i]}”</div>"
                 f"<div style='font-size:0.85rem'>true label <b>{t}</b> · model says "
                 f"P(positive) = {p_test[i]:.2f} → <b>{pr}</b></div>")
    return html + "</div>"

hdr, h0, h1 = st.columns([1, 3, 3])
h0.markdown("**model says 0 (negative)**")
h1.markdown("**model says 1 (positive)**")
for t in (0, 1):
    lab, c0, c1_ = st.columns([1, 3, 3])
    lab.markdown(f"**true label {t}**  \n({int(np.sum(test_y == t))} reviews)")
    c0.html(cell_html(t, 0))
    c1_.html(cell_html(t, 1))
st.caption("Rows: what the review really is. Columns: what the model said. "
           "Green cells are right, red cells are wrong. Each cell shows the "
           "review the model was most sure about in that cell.")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Model test AUC", f"{roc_auc_score(test_y, p_test):.3f}",
          help=f"Best possible on this test set: {ceiling_auc:.3f}")
c2.metric("Sensitivity", f"{sensitivity:.1%}", help=f"{tp} of {tp + fn} positives caught")
c3.metric("Specificity", f"{specificity:.1%}", help=f"{tn} of {tn + fp} negatives caught")
c4.metric("Accuracy", f"{model_acc:.1%}",
          help=f"{tp + tn} of {len(test_y)} right · best possible {ceiling_acc:.0%}")
st.markdown(f"""
- **AUC** — rank every review by its predicted probability; the chance that a
  random positive review is ranked above a random negative one. 0.5 = coin
  flip, 1.0 = perfect ranking. Needs no threshold.
- **Sensitivity** (recall, true positive rate) — of the reviews that ARE
  positive, the share the model called positive: TP / (TP + FN) = {tp} / {tp + fn}.
- **Specificity** (true negative rate) — of the reviews that ARE negative, the
  share the model called negative: TN / (TN + FP) = {tn} / {tn + fp}.
- **Accuracy** — share of all reviews the model got right:
  (TP + TN) / all = {tp + tn} / {len(test_y)}. Best possible here is
  {ceiling_acc:.0%}, because the ambiguous test reviews are coin flips.

Sensitivity, specificity and accuracy all depend on the 0.5 decision
boundary; AUC does not.
""")

# Show the student their own training function next to the numbers it produced.
st.markdown("**The model behind these numbers** — your `train_classifier()`, as it "
            "is in the file right now:")
st.code(inspect.getsource(train_classifier), language="python")
st.caption("Everything above the confusion matrix is scikit-learn's `LogisticRegression` "
           "fitted on the word-count matrix from `vectorize()`, with the class weight "
           "from the slider. The probabilities come from `predict_probs()`.")

# ================================================================ Part 3
st.markdown("---")
st.header("Part 3: Analysis of the model result")

c1, c2 = st.columns(2)
with c1:
    order = np.argsort(w)
    top = list(order[-8:][::-1]) + list(order[:8][::-1])
    fig, ax = plt.subplots(figsize=(6, 5))
    colors = ["#2ca02c" if w[i] > 0 else "#d62728" for i in top]
    ax.barh([vocab[i] for i in top], [w[i] for i in top], color=colors, alpha=0.8)
    ax.invert_yaxis()
    ax.set_title("What the model learned: strongest words")
    ax.set_xlabel("weight (green → positive, red → negative)")
    ax.grid(True, axis="x", alpha=0.3)
    st.pyplot(fig)
with c2:
    fig, ax = plt.subplots(figsize=(6, 5))
    ax.hist(p_test[test_y == 1], bins=15, alpha=0.6, color="#2ca02c", label="true positives")
    ax.hist(p_test[test_y == 0], bins=15, alpha=0.6, color="#d62728", label="true negatives")
    ax.axvline(0.5, color="black", linestyle="--", alpha=0.7, label="decision boundary")
    ax.set_title("Model's predicted probabilities (test set)")
    ax.set_xlabel("predicted P(positive)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    st.pyplot(fig)

# ------------------------------------------------- inspect a single review

st.subheader("Inspect a review: text → counts → prediction")

flt = st.radio("Show", ["model got it wrong", "model got it right", "all"],
               horizontal=True)
if flt == "model got it wrong":
    pool = np.where(model_pred != test_y)[0]
elif flt == "model got it right":
    pool = np.where(model_pred == test_y)[0]
else:
    pool = np.arange(len(test_texts))

sel = st.selectbox(
    "Test review", pool,
    format_func=lambda i: (f"#{i:02d} [{'✓' if model_pred[i] == test_y[i] else '✗'}] "
                           f"{test_texts[i][:70]}..."))

text = test_texts[sel]
word2idx = vectorizer.vocabulary_
wmax = np.abs(w).max()

def colorize(match):
    token = match.group(0).lower()
    if token in word2idx:
        wi = w[word2idx[token]]
        alpha = 0.15 + 0.55 * abs(wi) / wmax
        rgb = "44,160,44" if wi > 0 else "214,39,40"
        return (f"<span style='background: rgba({rgb},{alpha:.2f}); "
                f"border-radius:3px; padding:0 2px'>{match.group(0)}</span>")
    return f"<span style='color:#999'>{match.group(0)}</span>"

st.html("<div style='font-size:1.15rem; line-height:2.0'>"
        + re.sub(r"[A-Za-z']+", colorize, text) + "</div>")
st.caption("green = positive-weight word · red = negative-weight word · "
           "gray = not in the vocabulary (invisible to the model)")

row = np.asarray(vectorizer.transform([text]).todense()).ravel()
nz = np.where(row > 0)[0]
contrib = w[nz] * row[nz]
order = np.argsort(contrib)
labels = [f"{vocab[i]}" + (f" ×{int(row[i])}" if row[i] > 1 else "") for i in nz[order]]
bias = float(model.intercept_[0])
logit = bias + float(contrib.sum())
prob = 1 / (1 + np.exp(-logit))

fig = go.Figure(go.Waterfall(
    orientation="v",
    measure=["absolute"] + ["relative"] * len(labels) + ["total"],
    x=["bias"] + labels + ["logit"],
    y=[bias] + list(contrib[order]) + [0],
    decreasing=dict(marker=dict(color="#d62728")),
    increasing=dict(marker=dict(color="#2ca02c")),
    totals=dict(marker=dict(color="#1f77b4")),
    connector=dict(line=dict(color="lightgray"))))
fig.update_layout(
    title=(f"weight × count per word  →  logit {logit:+.2f}  →  "
           f"P(positive) = {prob:.2f}"),
    height=380, margin=dict(l=10, r=10, t=50, b=10), showlegend=False)
st.plotly_chart(fig, width="stretch")


# ------------------------------------------------- t-SNE map of the reviews

st.subheader("A map of all reviews (t-SNE)")

X_all = vectorizer.transform(train_texts + test_texts)
Y_all = tsne_embed(np.asarray(X_all.todense()))
p_all = np.asarray(predict_probs(model, X_all), dtype=float)
n_tr = len(train_texts)
Y_te = Y_all[n_tr:]

gx = np.linspace(Y_all[:, 0].min() - 2, Y_all[:, 0].max() + 2, 120)
gy = np.linspace(Y_all[:, 1].min() - 2, Y_all[:, 1].max() + 2, 120)
GX, GY = np.meshgrid(gx, gy)
grid = np.column_stack([GX.ravel(), GY.ravel()])
d2 = (np.sum(grid ** 2, 1)[:, None] + np.sum(Y_all ** 2, 1)[None, :]
      - 2 * grid @ Y_all.T)
nn = np.argsort(d2, axis=1)[:, :12]
prob_grid = p_all[nn].mean(axis=1).reshape(GX.shape)

def wrap(s, width=55):
    words, lines, cur = s.split(), [], ""
    for w_ in words:
        if len(cur) + len(w_) + 1 > width:
            lines.append(cur)
            cur = w_
        else:
            cur = f"{cur} {w_}".strip()
    lines.append(cur)
    return "<br>".join(lines)

fig = go.Figure()
fig.add_trace(go.Contour(
    x=gx, y=gy, z=prob_grid, colorscale="RdYlGn", opacity=0.30,
    contours=dict(start=0, end=1, size=0.05), line_width=0,
    showscale=False, hoverinfo="skip"))
fig.add_trace(go.Contour(
    x=gx, y=gy, z=prob_grid,
    contours=dict(start=0.5, end=0.5, size=1, coloring="lines"),
    line=dict(width=2.5, color="black", dash="dash"),
    showscale=False, hoverinfo="skip", name="approx. decision boundary",
    showlegend=True))
fig.add_trace(go.Scatter(
    x=Y_all[:n_tr, 0], y=Y_all[:n_tr, 1], mode="markers",
    marker=dict(size=5, color="gray", opacity=0.3),
    name="training reviews",
    hovertext=[f"{wrap(train_texts[i])}<br><b>label: {train_y[i]}"
               f" · model says {p_all[i]:.2f}</b>" for i in range(n_tr)],
    hoverinfo="text"))
cats = [("true pos, model right", (test_y == 1) & (model_pred == 1), "#2ca02c", "circle"),
        ("true pos, model WRONG", (test_y == 1) & (model_pred == 0), "#2ca02c", "x"),
        ("true neg, model right", (test_y == 0) & (model_pred == 0), "#d62728", "circle"),
        ("true neg, model WRONG", (test_y == 0) & (model_pred == 1), "#d62728", "x")]
for label, mask, color, symbol in cats:
    idx = np.where(mask)[0]
    fig.add_trace(go.Scatter(
        x=Y_te[idx, 0], y=Y_te[idx, 1], mode="markers",
        marker=dict(size=11, color=color, symbol=symbol,
                    line=dict(width=1, color="black")),
        name=f"{label} ({len(idx)})",
        hovertext=[f"{wrap(test_texts[i])}<br><b>true: {test_y[i]}"
                   f" · model: {model_pred[i]} ({p_test[i]:.2f})</b>" for i in idx],
        hoverinfo="text"))
fig.update_layout(
    title="t-SNE map — hover any point to read the review",
    xaxis=dict(visible=False), yaxis=dict(visible=False),
    height=620, legend=dict(font=dict(size=11)),
    margin=dict(l=10, r=10, t=40, b=10))
st.plotly_chart(fig, width="stretch")

# ================================================================ Part 4
st.markdown("---")
st.header("Part 4: The challenger — Claude Haiku")

if not MY_PROMPT.strip():
    st.warning("Part A complete! Now write `MY_PROMPT` — the instruction that "
               "turns Haiku into a review classifier. It is sent together with "
               "each batch of 10 reviews by your `ask_haiku()`.")
    st.stop()

st.markdown("The prompt your `ask_haiku()` sends with every batch of 10 reviews. "
            "**Edit it here to experiment** — then copy the version you like best "
            "back into `MY_PROMPT` in the file, because the file is what you submit.")
prompt = st.text_area("Prompt", MY_PROMPT, height=140, label_visibility="collapsed")
if prompt.strip() != MY_PROMPT.strip():
    st.caption("This prompt differs from `MY_PROMPT` in the file. Keep the answer "
               "format your `ask_haiku()` expects, or its parser will fall back to 50.")

api_key = os.environ.get("ANTHROPIC_API_KEY", "")
if not api_key:
    # walk up from this file until a .env is found (the repository root)
    for folder in [HERE, *HERE.parents]:
        env = folder / ".env"
        if env.exists():
            for line in env.read_text().splitlines():
                if line.strip().startswith("ANTHROPIC_API_KEY="):
                    api_key = line.split("=", 1)[1].strip()
            break

n_reviews = st.slider("Number of test reviews to send", 10, len(test_texts),
                      len(test_texts), 10)
if not api_key:
    st.warning("No API key found (checked the environment and the repo .env).")
elif st.button(f"Ask Haiku to rate {n_reviews} reviews", type="primary"):
    # The reviews go out in batches of BATCH, all batches at the same time
    # (one thread each), so 100 reviews take one round trip, not 100.
    BATCH = 10
    starts = list(range(0, n_reviews, BATCH))
    batches = [test_texts[s:min(s + BATCH, n_reviews)] for s in starts]
    scores = np.full(len(test_texts), np.nan)
    bar = st.progress(0.0, text=f"Asking Haiku ({len(batches)} batches of {BATCH})...")
    done, problem = 0, None
    with ThreadPoolExecutor(max_workers=len(batches)) as pool:
        futures = [pool.submit(ask_haiku, api_key, prompt, b) for b in batches]
        for s, b, fut in zip(starts, batches, futures):
            try:
                out = list(fut.result())
            except requests.exceptions.ConnectionError:
                problem = ("Network problem — could not reach api.anthropic.com. "
                           "Check your internet connection (Wi-Fi/VPN/DNS) and "
                           "click the button again.")
                continue
            except requests.exceptions.HTTPError as e:
                problem = f"The API rejected the request: {e.response.text[:300]}"
                continue
            if len(out) != len(b):
                problem = (f"`ask_haiku()` returned {len(out)} scores for a batch of "
                           f"{len(b)} reviews — it must return exactly one score per "
                           "review, in order.")
                continue
            scores[s:s + len(b)] = out
            done += len(b)
            bar.progress(done / n_reviews, text=f"Asking Haiku... {done}/{n_reviews}")
    bar.empty()
    if problem:
        st.error(problem)
    if done == n_reviews:
        st.session_state["llm_scores"] = scores
        st.session_state["llm_n"] = done
        st.session_state["llm_prompt"] = prompt

# ================================================================ Part 5
if "llm_scores" in st.session_state:
    st.markdown("---")
    st.header("Part 5: Head to head")
    if st.session_state["llm_prompt"].strip() != prompt.strip():
        st.info("These Haiku scores came from an earlier prompt. Click the button "
                "above to re-rate the reviews with the prompt you have now.")
    st.caption("The test set is pinned, so these Haiku scores stay valid while "
               "you change the training sliders above and retrain your model.")

    n = st.session_state["llm_n"]
    raw = st.session_state["llm_scores"][:n]
    if np.all(raw == 50):
        st.warning("Every Haiku score came back exactly 50 — that's the "
                   "placeholder `ask_haiku()` (or every call silently failed). "
                   "Implement it, and make sure the model ID is exactly "
                   "claude-haiku-4-5.")
        st.stop()

    llm_scores = raw / 100.0
    sub_y, sub_texts = test_y[:n], test_texts[:n]
    sub_model_p, sub_model_pred = p_test[:n], model_pred[:n]
    llm_pred = (llm_scores >= 0.5).astype(int)

    llm_acc = float(np.mean(llm_pred == sub_y))
    llm_auc = roc_auc_score(sub_y, llm_scores)
    sub_model_acc = float(np.mean(sub_model_pred == sub_y))
    sub_model_auc = roc_auc_score(sub_y, sub_model_p)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Your model — accuracy", f"{sub_model_acc:.1%}")
    c2.metric("Haiku — accuracy", f"{llm_acc:.1%}",
              delta=f"{llm_acc - sub_model_acc:+.1%}")
    c3.metric("Your model — AUC", f"{sub_model_auc:.3f}")
    c4.metric("Haiku — AUC", f"{llm_auc:.3f}", delta=f"{llm_auc - sub_model_auc:+.3f}")

    c1, c2 = st.columns(2)
    with c1:
        fig, ax = plt.subplots(figsize=(6, 5))
        for name, s_, color in [("Your model", sub_model_p, "#1f77b4"),
                                ("Haiku", llm_scores, "#ff7f0e")]:
            fpr, tpr, _ = roc_curve(sub_y, s_)
            ax.plot(fpr, tpr, color=color, linewidth=2.5,
                    label=f"{name} (AUC {roc_auc_score(sub_y, s_):.3f})")
        ax.plot([0, 1], [0, 1], "k--", alpha=0.4, label="coin flip")
        ax.set_xlabel("False positive rate")
        ax.set_ylabel("True positive rate")
        ax.set_title(f"ROC curves — the ceiling is {ceiling_auc:.2f} for everyone")
        ax.legend()
        ax.grid(True, alpha=0.3)
        st.pyplot(fig)
    with c2:
        fig, axes = plt.subplots(1, 2, figsize=(7, 3.2))
        for ax, name, pred in [(axes[0], "Your model", sub_model_pred),
                               (axes[1], "Haiku", llm_pred)]:
            cm = confusion_matrix(sub_y, pred)
            ax.imshow(cm, cmap="Blues", vmin=0)
            for r in range(2):
                for c in range(2):
                    ax.text(c, r, cm[r, c], ha="center", va="center",
                            color="black", fontsize=13)
            ax.set_xticks([0, 1], ["pred 0", "pred 1"])
            ax.set_yticks([0, 1], ["true 0", "true 1"])
            ax.set_title(name)
        plt.tight_layout()
        st.pyplot(fig)

    disagree = np.where(sub_model_pred != llm_pred)[0]
    st.subheader(f"Where they disagree ({len(disagree)} of {n} reviews)")
    for i in disagree[:8]:
        winner = ("Haiku" if llm_pred[i] == sub_y[i] else
                  "Your model" if sub_model_pred[i] == sub_y[i] else "nobody")
        st.markdown(
            f"> {sub_texts[i]}  \n"
            f"> — true: **{sub_y[i]}** · {test_kind[i]} · model: {sub_model_pred[i]} "
            f"({sub_model_p[i]:.2f}) · Haiku: {llm_pred[i]} "
            f"({llm_scores[i]:.2f}) · point to **{winner}**")
